# Generated by Django 3.2.6 on 2021-08-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(default='', max_length=25)),
                ('username', models.CharField(default='', max_length=25)),
                ('password', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
