# Generated by Django 3.2.6 on 2021-08-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
